import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../globals.css";

import NextTopLoader from "nextjs-toploader";
import { NextIntlClientProvider } from "next-intl";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <NextIntlClientProvider>
          <NextTopLoader />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
