import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../globals.css";

import NextTopLoader from "nextjs-toploader";
import { NextIntlClientProvider } from "next-intl";

import { Toast } from "@/components/ui/toast";

import AuthProvider from "@/components/providers/auth-provider";
import NuqsProvider from "@/components/providers/nuqs-provider";
import QueryProvider from "@/components/providers/query-provider";
import ThemeProvider from "@/components/providers/theme-provider";
import RecaptchaProvider from "@/components/providers/recaptcha-provider";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <QueryProvider>
          <RecaptchaProvider>
            <NuqsProvider>
              <ThemeProvider>
                <NextIntlClientProvider>
                  <AuthProvider>
                    <Toast />
                    <NextTopLoader />
                    {children}
                  </AuthProvider>
                </NextIntlClientProvider>
              </ThemeProvider>
            </NuqsProvider>
          </RecaptchaProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
